version: "3.3"
services:
  go-server:
    image: fadhilradh/progressme-api
    container_name: progressme-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - progressme-network
  cache:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
      - progressme-network
  postgres:
    container_name: postgres-13
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=skygazer
      - POSTGRES_PASSWORD=hamdalah
      - POSTGRES_DB=progressme
      - PGDATA=/data/postgres
    ports:
      - "5232:5432"
    expose:
      - 5232
    volumes:
      - postgres:/data/postgres
    networks:
      - progressme-network

volumes:
  postgres:
  redis:
networks:
  progressme-network:
    driver: bridge
