// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chart struct {
	ID           uuid.UUID     `json:"id"`
	UserID       uuid.NullUUID `json:"user_id"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
	RangeType    *string       `json:"range_type"`
	ProgressName *string       `json:"progress_name"`
	Colors       *string       `json:"colors"`
	ChartType    *string       `json:"chart_type"`
	BarChartType *string       `json:"bar_chart_type"`
}

type Progress struct {
	ID            uuid.UUID     `json:"id"`
	ChartID       uuid.NullUUID `json:"chart_id"`
	ProgressValue *int64        `json:"progress_value"`
	RangeValue    *string       `json:"range_value"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
	ProgressNo    *int32        `json:"progress_no"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	Username        string         `json:"username"`
	Email           string         `json:"email"`
	Password        string         `json:"password"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	Role            string         `json:"role"`
	PhotoProfileUrl sql.NullString `json:"photo_profile_url"`
}
