// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addClerkUser = `-- name: AddClerkUser :one
INSERT INTO users(id, created_at) 
VALUES($1, now())
RETURNING id, created_at, updated_at
`

type AddClerkUserRow struct {
	ID        string       `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (q *Queries) AddClerkUser(ctx context.Context, id string) (AddClerkUserRow, error) {
	row := q.db.QueryRowContext(ctx, addClerkUser, id)
	var i AddClerkUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(username, email, password, created_at, updated_at, role)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, role, created_at, updated_at
`

type CreateUserParams struct {
	Username  sql.NullString `json:"username"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Role      sql.NullString `json:"role"`
}

type CreateUserRow struct {
	ID        string         `json:"id"`
	Username  sql.NullString `json:"username"`
	Email     sql.NullString `json:"email"`
	Role      sql.NullString `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, created_at, updated_at, role, photo_profile_url FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.PhotoProfileUrl,
	)
	return i, err
}
